

services:
  server:
    build: ./server
    container_name: codesync-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://tharunkunamalla7_db_user:tharun701@cluster0.c1jxg0t.mongodb.net/?appName=Cluster0
    restart: always

  client:
    build: 
      context: ./client
      args:
        - VITE_PISTON_URL=/piston/api/v2/execute
    container_name: codesync-client
    ports:
      - "5173:80"
    depends_on:
      - server
      - piston
    restart: always

  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: codesync-piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-data:/piston
    tmpfs:
      - /tmp:exec,mode=777
    restart: always

volumes:
  piston-data:
